logpath: "log.log"

scraper:
  doctors_overview:
    url: https://www.mchk.org.hk/english/list_register/list.php?ipp=20&type=L
    num_pages: 767 # number of pages on overview website
    output_path: ./data/scraped_doctors_overview.json

  doctors_detail:
    url: https://www.mchk.org.hk/english/list_register/doctor_detail.php?reg_no=
    output_path: ./data/scraped_doctors_detail.json
    batch_size: 3000

  datapath: ./data/

elasticsearch:
  certs_path: ./http_ca.crt
  host_path: https://localhost:9200
